void adc(uint32_t addr);
void sbc(uint32_t addr);
void and(uint32_t addr);
void ora(uint32_t addr);
void eor(uint32_t addr);
void lda(uint32_t addr);
void st(uint32_t addr, uint32_t val);
void cmp(uint32_t reg, uint32_t addr);
void asl(uint32_t addr);
void lsr(uint32_t addr);
void rol(uint32_t addr);
void ror(uint32_t addr);
void inc(uint32_t addr);
void dec(uint32_t addr);
void br(uint32_t cond);
void func_adc_zpxi(void);
void func_adc_zp(void);
void func_adc_imm(void);
void func_adc_abs(void);
void func_adc_zpiy(void);
void func_adc_zpx(void);
void func_adc_absy(void);
void func_adc_absx(void);
void func_sbc_zpxi(void);
void func_sbc_zp(void);
void func_sbc_imm(void);
void func_sbc_abs(void);
void func_sbc_zpiy(void);
void func_sbc_zpx(void);
void func_sbc_absy(void);
void func_sbc_absx(void);
void func_and_zpxi(void);
void func_and_zp(void);
void func_and_imm(void);
void func_and_abs(void);
void func_and_zpiy(void);
void func_and_zpx(void);
void func_and_absy(void);
void func_and_absx(void);
void func_ora_zpxi(void);
void func_ora_zp(void);
void func_ora_imm(void);
void func_ora_abs(void);
void func_ora_zpiy(void);
void func_ora_zpx(void);
void func_ora_absy(void);
void func_ora_absx(void);
void func_eor_zpxi(void);
void func_eor_zp(void);
void func_eor_imm(void);
void func_eor_abs(void);
void func_eor_zpiy(void);
void func_eor_zpx(void);
void func_eor_absy(void);
void func_eor_absx(void);
void func_lda_zpxi(void);
void func_lda_zp(void);
void func_lda_imm(void);
void func_lda_abs(void);
void func_lda_zpiy(void);
void func_lda_zpx(void);
void func_lda_absy(void);
void func_lda_absx(void);
void func_sta_zpxi(void);
void func_sta_zp(void);
void func_sta_abs(void);
void func_sta_zpiy(void);
void func_sta_zpx(void);
void func_sta_absy(void);
void func_sta_absx(void);
void func_cmp_zpxi(void);
void func_cmp_zp(void);
void func_cmp_imm(void);
void func_cmp_abs(void);
void func_cmp_zpiy(void);
void func_cmp_zpx(void);
void func_cmp_absy(void);
void func_cmp_absx(void);
void func_lsr_zp(void);
void func_lsr_acc(void);
void func_lsr_abs(void);
void func_lsr_zpx(void);
void func_lsr_absx(void);
void func_asl_zp(void);
void func_asl_acc(void);
void func_asl_abs(void);
void func_asl_zpx(void);
void func_asl_absx(void);
void func_rol_zp(void);
void func_rol_acc(void);
void func_rol_abs(void);
void func_rol_zpx(void);
void func_rol_absx(void);
void func_ror_zp(void);
void func_ror_acc(void);
void func_ror_abs(void);
void func_ror_zpx(void);
void func_ror_absx(void);
void func_ldx_imm(void);
void func_ldx_zp(void);
void func_ldx_abs(void);
void func_ldx_zpy(void);
void func_ldx_absy(void);
void func_stx_zp(void);
void func_stx_abs(void);
void func_stx_zpy(void);
void func_ldy_imm(void);
void func_ldy_zp(void);
void func_ldy_abs(void);
void func_ldy_zpx(void);
void func_ldy_absx(void);
void func_sty_zp(void);
void func_sty_abs(void);
void func_sty_zpx(void);
void func_dec_zp(void);
void func_dec_abs(void);
void func_dec_zpx(void);
void func_dec_absx(void);
void func_inc_zp(void);
void func_inc_abs(void);
void func_inc_zpx(void);
void func_inc_absx(void);
void func_cpx_imm(void);
void func_cpx_zp(void);
void func_cpx_abs(void);
void func_cpy_imm(void);
void func_cpy_zp(void);
void func_cpy_abs(void);
void func_bit_zp(void);
void func_bit_abs(void);
void func_jmp(void);
void func_jmpi(void);
void func_jsr(void);
void func_rts(void);
void func_rti(void);
void func_inx(void);
void func_dex(void);
void func_iny(void);
void func_dey(void);
void func_clc(void);
void func_sec(void);
void func_cli(void);
void func_sti(void);
void func_cld(void);
void func_std(void);
void func_clv(void);
void func_tax(void);
void func_txa(void);
void func_tay(void);
void func_tya(void);
void func_tsx(void);
void func_txs(void);
void func_bpl(void);
void func_bmi(void);
void func_bvc(void);
void func_bvs(void);
void func_bcc(void);
void func_bcs(void);
void func_bne(void);
void func_beq(void);
void func_php(void);
void func_plp(void);
void func_pha(void);
void func_pla(void);
void func_brk(void);
void func_nop(void);
void func_undef(void);
int main(int argc, char *argv[]);
int readfile(char *filename);
void scan_file(int k);
void scan_line(void);
struct sym * scan_label(void);
void scan_addr(void);
void scan_expr(void);
void scan_term(void);
void scan_factor(void);
void scan_error(char *errmsg);
struct sym * scan_lookup(void);
void scan_token(void);
void scan_branch(void);
void scan_value(void);
void scan_adc(void);
void scan_and(void);
void scan_asl(void);
void scan_bcc(void);
void scan_bcs(void);
void scan_beq(void);
void scan_bit(void);
void scan_bmi(void);
void scan_bne(void);
void scan_bpl(void);
void scan_brk(void);
void scan_bvc(void);
void scan_bvs(void);
void scan_clc(void);
void scan_cld(void);
void scan_cli(void);
void scan_clv(void);
void scan_cmp(void);
void scan_cpx(void);
void scan_cpy(void);
void scan_dec(void);
void scan_dex(void);
void scan_dey(void);
void scan_eor(void);
void scan_inc(void);
void scan_inx(void);
void scan_iny(void);
void scan_jmp(void);
void scan_jsr(void);
void scan_lda(void);
void scan_ldx(void);
void scan_ldy(void);
void scan_lsr(void);
void scan_nop(void);
void scan_ora(void);
void scan_pha(void);
void scan_php(void);
void scan_pla(void);
void scan_plp(void);
void scan_rol(void);
void scan_ror(void);
void scan_rti(void);
void scan_rts(void);
void scan_sbc(void);
void scan_sec(void);
void scan_sed(void);
void scan_sei(void);
void scan_sta(void);
void scan_stx(void);
void scan_sty(void);
void scan_tax(void);
void scan_tay(void);
void scan_tsx(void);
void scan_txa(void);
void scan_txs(void);
void scan_tya(void);
void scan_emit(int opcode, int count);
void scan_bss(void);
void scan_byte(void);
void scan_word(void);
void scan_emit_byte(int byte);
void scan_emit_word(int word);
void stack_push(int value);
int stack_pop(void);
void stack_add(void);
void stack_sub(void);
void stack_neg(void);
void stack_mul(void);
void stack_div(void);
void stack_rem(void);
void stack_and(void);
void stack_or(void);
void stack_xor(void);
void stack_cpl(void);
void stack_shr(void);
void stack_shl(void);
